/**
 * @file Contains specification of an SRTC Identity Provider.
 * @module secure-webrtc
 * @author Jonas Primbs <mail@jonasprimbs.de>
 * @license MIT
 * @copyright Jonas Primbs 2021
 * @version 0.0.1
 */

export interface SRTCIdentityProvider {

  /**
   * Public key used to validate signatures generated by identity provider.
   * If not specified, public key will loaded from identity provider via OIDC endpoint.
   */
  publicKey?: CryptoKey;

  /**
   * Full URL of identity provider's OIDC endpoint.
   * @example "https://idp.example.org/realm"
   */
  url: string;
}
